# Site settings
title: isoverse
github: isoverse
ga: UA-106138361-6
description: >
  open-source data tools for stable isotopes
url: "https://isoverse.org"
logo: "/images/logos/isoverse_logo_thumb.png"
icon: "/images/isoverse_icon.png"
permalink: /:categories/:title/

# Build settings
markdown: kramdown

# Data
collections:
  packages:
    output: true
    permalink: /:collection/:path/
  resources:
    output: true
    permalink: /:path/
